Repository Jandy-SeoulTech/Jandy_Web_Back, pull requests merged in 2021-10, with the labels that each got.

#73 AWS s3 이미지 업로드 기능
  package-lock.json
  package.json
  src/configs/index.js
  src/configs/s3.js
  src/services/ImageServices.js
Labels: Feature ✨, Refactoring 🚜

#71 AWS migration에서 Dockerfile 픽스 필요
  Dockerfile
  server.update.sh
  src/index.js
Labels: Bug 🐛

#75 Feat/issue 67
  package-lock.json
  prisma/schema.prisma
  server.update.sh
  src/controllers/ArchiveController.js
  src/index.js
  src/repositories/ArchiveRepository.js
  src/repositories/PostRepository.js
  src/repositories/UserRepository.js
  src/services/ArchiveServices.js
  src/validations/ArchiveValidation.js
Labels: Feature ✨

#77 Feat: api/Comment GET 엔드포인트 작성
  prisma/schema.prisma
  src/controllers/CommentContoller.js
  src/repositories/ArchiveRepository.js
  src/repositories/CommentRepository.js
  src/repositories/PostRepository.js
  src/services/CommentServices.js
  src/validations/CommentValidation.js
Labels: Feature ✨

#79 채팅방 - archive 연동 API #68
  package-lock.json
  prisma/schema.prisma
  src/controllers/ChatController.js
  src/controllers/RoomController.js
  src/repositories/ChannelRoomRepository.js
  src/repositories/ChatMessageRepository.js
  src/services/ArchiveServices.js
  src/services/ChatServices.js
  src/services/RoomServices.js
  src/validations/ChatValidation.js
Labels: Feature ✨

#145 fix : 참조무결성을 위한 action (#144)
  package-lock.json
  prisma/schema.prisma
  src/services/PostServices.js
Labels: Bug 🐛
