Repository Jandy-SeoulTech/Jandy_Web_Back, pull requests merged in 2021-09, with the labels that each got.

#46 feat:eslint, prettier 추가 및 코드 eslint에맞게 변경
  .eslintrc
  .prettierrc
  package-lock.json
  package.json
  src/configs/email.js
  src/configs/passport/OAuthStrategy.js
  src/controllers/OAuthController.js
  src/controllers/SearchController.js
  src/repositories/AttentionRepository.js
  src/repositories/AuthRepository.js
  src/repositories/BanRepository.js
  src/repositories/CommentRepository.js
  src/repositories/LikeReposiotry.js
  src/repositories/ReviewRepository.js
  src/services/AuthServices.js
  src/services/ChannelServices.js
  src/services/CommentServices.js
  src/services/OauthServices.js
  src/services/PostServices.js
  src/services/ProfileServices.js
  src/services/RoomServices.js
  src/services/SearchServices.js
  src/validations/ChannelValidation.js
  src/validations/CommentValidation.js
  src/validations/PostValidation.js
  src/validations/SearchValidation.js
Labels: Feature, Refactor

#49 OAuth, Channel, Post, Comment 1차 리팩토링
  package-lock.json
  src/controllers/ChannelController.js
  src/controllers/CommentContoller.js
  src/controllers/PostController.js
  src/index.js
  src/repositories/CommentRepository.js
  src/repositories/PostRepository.js
  src/services/ChannelServices.js
  src/services/CommentServices.js
  src/services/PostServices.js
  src/validations/ChannelValidation.js
  src/validations/CommentValidation.js
Labels: Refactor

#52 Profile, Chat, Room Refactoring
  src/controllers/ProfileController.js
  src/controllers/ReviewController.js
  src/controllers/RoomController.js
  src/index.js
  src/repositories/ChannelRepository.js
  src/repositories/ChannelRoomRepository.js
  src/repositories/ChatMessageRepository.js
  src/repositories/UserRepository.js
  src/services/ChatServices.js
  src/services/ProfileServices.js
  src/services/ReviewServices.js
  src/services/RoomServices.js
  src/validations/AuthValidation.js
  src/validations/ChatValidation.js
  src/validations/ProfileValidation.js
  src/validations/ReviewValidation.js
  src/validations/RoomValidation.js
Labels: Refactor

#58 Api Bug Report
  src/repositories/UserRepository.js
  src/services/ProfileServices.js
Labels: bug, Feature

#61 migration from GCP to AWS With Docker
  .dockerignore
  .github/PULL_REQUEST_TEMPLATE.md
  Dockerfile
  package-lock.json
  package.json
  server.update.sh
  src/index.js
Labels: Feature ✨

#62 migration from GCP to AWS With Docker
  server.update.sh
  src/index.js
Labels: Bug 🐛
